In [103]:
import numpy as np
import pandas as pd
import mplcursors
import matplotlib.pyplot as plt
from mpl_toolkits import mplot3d

In [104]:
content = pd.read_csv('../result/FG_anchor_6.csv', header=None)
Opt_anchor = content.values
Opt_anchor -= Opt_anchor[2]
Opt_anchor = Opt_anchor[:,:-1]
Opt_anchor[1] = [100, 100]

content = pd.read_csv('GT_pose_6.csv', header=None)
GT_pose = content.values
GT_pose = GT_pose[:,:-1]
GT_pose += Opt_anchor[-1] - GT_pose[0]

content = pd.read_csv('Anchor_GT.csv', header=None)
GT_anchor = content.values

content = pd.read_csv('encoder_6.csv', header=None)
encoder = content.values

In [105]:
l = []
for pose in GT_pose:
    m = np.linalg.norm(pose - Opt_anchor[0])
    n = np.linalg.norm(pose - Opt_anchor[1])
    k = np.linalg.norm(pose - Opt_anchor[2])
    h = np.linalg.norm(pose - Opt_anchor[3])
    l.append([m+n, m+2*k, n+2*h])
    
l = np.array(l) - np.array(l[0])

r = [0.025, 0.035, 0.035]
l_enc = []
for enc in encoder:
    l_enc.append(r*enc)

error = l - l_enc
print(error)

[[ 0.          0.          0.        ]
 [ 0.01431596 -0.00621083  0.00329875]
 [ 0.00054427 -0.00091358  0.00332823]
 [-0.05423522  0.00466652 -0.04226433]
 [ 0.00910443  0.0014658   0.00864187]
 [ 0.01535713 -0.0107861  -0.00083543]
 [-0.00081463 -0.00040913 -0.00379774]
 [-0.03764579 -0.00300612 -0.03162045]
 [-0.06945803  0.00380039 -0.05299781]
 [ 0.01131156  0.00056082  0.00546234]
 [ 0.0182993  -0.00499724  0.00165093]
 [-0.06587338  0.00650029 -0.05143537]
 [ 0.01689984 -0.00682888  0.00258351]
 [ 0.00972281 -0.00070122  0.00256423]
 [-0.02658126  0.00098125 -0.02416604]
 [-0.04551331  0.00368713 -0.03804023]
 [-0.07286751  0.00495659 -0.05665938]
 [-0.0253786   0.00456909 -0.02015741]
 [ 0.00718307 -0.00077807  0.00402958]
 [-0.03115549  0.00283846 -0.027428  ]
 [-0.11044595  0.00274957 -0.07979042]
 [-0.00474184  0.0014922  -0.00532368]
 [ 0.00991014 -0.00394226  0.00213665]
 [ 0.00922653  0.00044875  0.00980675]
 [ 0.00858448  0.00122017  0.00719026]
 [ 0.00843382 -0.00226741

In [106]:
fig = plt.figure()

%matplotlib qt

plt.plot(GT_pose[:,0], GT_pose[:,1], label="Ground Truth Poses", linestyle='--', marker='o')
plt.scatter(GT_anchor[:-1,0], GT_anchor[:-1,1], label="Motion Capture")
plt.scatter(Opt_anchor[:,0], Opt_anchor[:,1], label="Optimization")
for i, (x, y) in enumerate(GT_anchor[:-1,:]):
    plt.text(x + 0.01, y + 0.01, f'$A_{i+1}$', color='blue', fontsize=12)

mplcursors.cursor(multiple=True)
plt.legend()
plt.show()

can't invoke "event" command: application has been destroyed
    while executing
"event generate $w <<ThemeChanged>>"
    (procedure "ttk::ThemeChanged" line 6)
    invoked from within
"ttk::ThemeChanged"
